### ISSUE TITLE
Don't work with cinnamon 3.2.7

### ISSUE THREAD

**Issue by NiXuB86** [hulygun/services-launcher#2]
Glass.log
<----------------
checkService@/home/egor/.local/share/cinnamon/applets/serviceLauncher@hulygun/applet.js:68
MyApplet.prototype.refresh/<@/home/egor/.local/share/cinnamon/applets/serviceLauncher@hulygun/applet.js:42
MyApplet.prototype.refresh@/home/egor/.local/share/cinnamon/applets/serviceLauncher@hulygun/applet.js:39
MyApplet.prototype._init@/home/egor/.local/share/cinnamon/applets/serviceLauncher@hulygun/applet.js:27
MyApplet@/home/egor/.local/share/cinnamon/applets/serviceLauncher@hulygun/applet.js:15
main@/home/egor/.local/share/cinnamon/applets/serviceLauncher@hulygun/applet.js:84
createApplet@/usr/share/cinnamon/js/ui/appletManager.js:404
addAppletToPanels@/usr/share/cinnamon/js/ui/appletManager.js:294
finishExtensionLoad@/usr/share/cinnamon/js/ui/appletManager.js:59
loadExtension@/usr/share/cinnamon/js/ui/extension.js:451
onEnabledAppletsChanged@/usr/share/cinnamon/js/ui/appletManager.js:235
---------------->
error t=2017-03-11T15:25:56.049Z [Applet "serviceLauncher@hulygun"]: Failed to evaluate 'main' function on applet: serviceLauncher@hulygun/67
error t=2017-03-11T15:25:56.050Z Could not load applet serviceLauncher@hulygun
info t=2017-03-11T15:25:56.054Z Hiding systray: network
info t=2017-03-11T15:25:56.056Z Adding systray: mintupdate.py (24x24px)
info t=2017-03-11T15:25:56.119Z Hiding systray: network
info t=2017-03-11T15:25:56.120Z Adding systray: mintupdate.py (24x24px)
info t=2017-03-11T15:25:57.624Z Resized mintupdate.py with normalized size (22x22px)

**Comment by hulygun** [comment]
@NiXuB86 Snx for issue. Reinstall applet, pls from master branch

**Comment by NiXuB86** [comment]
Thank you, I solve my problem with run this applet on arch with cinnamon 3.2.8
